backend:
  name: github
  repo: lozit/recettes
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Articles
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: "Tags", name: "tags", widget: "list"}
      - { name: body, label: Body, widget: markdown }